shop/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, ProfileView, ChangeProfileView, UserPasswordChangeView

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('registration/', RegisterView.as_view(), name="registration"),
    path("<int:pk>/", ProfileView.as_view(), name="profile"),
    path('<int:pk>/change/', ChangeProfileView.as_view(), name="change_profile"),
    path('change/password', UserPasswordChangeView.as_view(), name='password_change')
]

shop/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

api_url = [
    path('v1/', include('app_v1.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls")),
    path('api/', include(api_url)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models


# Create your models here.

class Profile(models.Model):
    birthday = models.DateField(null=True, blank=True, verbose_name="Birthday")
    avatar = models.ImageField(upload_to="avatars", null=True, blank=True, verbose_name="Avatar")
    user = models.OneToOneField(get_user_model(),
                                on_delete=models.CASCADE,
                                verbose_name="User",
                                related_name="profile")

    def __str__(self):
        return f"{self.id}. {self.user}: {self.birthday}"

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

shop/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import validate_email

from accounts.models import Profile


class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField(max_length=200, required=True, validators=[validate_email])

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['last_name'] == '':
            if cleaned_data['first_name'] == '':
                raise forms.ValidationError("Заполните одно из полей - Имя или Фамилию")
            return cleaned_data
        return cleaned_data

    class Meta(UserCreationForm.Meta):
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']


class UserChangeForm(forms.ModelForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'First name', 'last_name': 'Last name', 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'birthday']

shop/accounts/views.py
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import login, get_user_model
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView, UpdateView
from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from accounts.models import Profile


class RegisterView(CreateView):
    model = User
    template_name = 'registration.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:home')
        return next_url


class ProfileView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = "profile.html"
    context_object_name = "user_obj"


class ChangeProfileView(PermissionRequiredMixin, UpdateView):
    model = User
    form_class = UserChangeForm
    template_name = "change_user.html"
    profile_form_class = ProfileChangeForm
    context_object_name = "user_obj"

    def has_permission(self):
        return self.request.user.is_superuser or self.request.user == self.get_object()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "profile_form" not in context:
            context["profile_form"] = self.profile_form_class(instance=self.get_object().profile)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object, data=request.POST)
        profile_form = self.profile_form_class(instance=self.object.profile,
                                               data=request.POST,
                                               files=request.FILES)
        if form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        # self.get_form()
        form.save()
        profile_form.save()
        return redirect("accounts:profile", self.object.pk)

    def form_invalid(self, form, profile_form):
        return self.render_to_response(self.get_context_data(form=form, profile_form=profile_form))


class UserPasswordChangeView(PasswordChangeView):
    template_name = 'change_password.html'

    def get_success_url(self):
        return reverse('accounts:profile', kwargs={"pk": self.request.user.pk})

shop/accounts/templates/change_password.html
{% extends "base.html" %}
{% block title %}New password{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>New password</h1>
        <form action="" method="post">
            {% include "partial/form.html" with button_text="Save changes" %}
        </form>
    </div>
{% endblock %}

shop/accounts/templates/change_user.html
{% extends "base.html" %}
{% load static %}
{% block title %}Update profile{% endblock %}

{% block content %}
    <div class="container">
        <h1>Update profile</h1>
        <form action="" method="post" enctype="multipart/form-data">

            {% include "partial/form.html" with  fields_only=True %}
            {% include "partial/form.html" with form=profile_form button_text="Update" %}
        </form>
    </div>

{% endblock %}

shop/accounts/templates/login.html
{% extends "base.html" %}

{% block title %}Sign in{% endblock %}
{% block content %}
    <div class="text-center">
    <h1>Sign in</h1>
        <form  method="post" class="w-50 ms-auto me-auto">
            {% csrf_token %}
            {% if has_error %}
                <p class="text-danger">Wrong username or password</p>
            {% endif %}
            <div class="form-group">
                <label for="username" class="form-label">Username:</label>
                <input type="text" name="username" class="form-control" id="username">
            </div>
            <div class="form-group">
                <label for="password" class="form-label">Password:</label>
                <input type="password" name="password" class="form-control" id="password">
            </div>
            <button class="mt-3 btn btn-outline-dark" type="submit">Sign in</button>
        </form>
    </div>
{% endblock %}

shop/accounts/templates/profile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}
{% block nav_add %}
    {% if user_obj == user %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change_profile' user_obj.pk %}">Update profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url "accounts:password_change" %}">Change password</a>
        </li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="card flex-row mt-3">
        {% if user_obj.profile.avatar %}
            <img src="{{ user_obj.profile.avatar.url }}" class="card-img-top w-25" alt="...">
        {% endif %}
        <div class="card-body ms-5">
            <h5 class="card-title">Username: {{ user_obj.username }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">First name: {{ user_obj.first_name }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Last name: {{ user_obj.last_name }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Birthday: {{ user_obj.profile.birthday }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">E-mail: {{ user_obj.email }}</h6>
        </div>

    </div>

{% endblock %}

shop/accounts/templates/registration.html
{% extends "base.html" %}
    {% block title %}Registration{% endblock %}
    {% block content %}
        <div class="container mb-4">
            <h1>Registration</h1>
            <form method="post">
                {% for error in form.non_field_errors %}
                    <p class="text-danger">{{ error }}</p>
                {% endfor %}
            {% include 'partial/form.html' with button_text='Sign up' %}
            </form>
        </div>
{% endblock %}