shop/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

api_url = [
    path('v1/', include('app_v1.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls")),
    path('api/', include(api_url)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/webapp/urls.py
from django.urls import path

from webapp.views import IndexView, ItemView, CreateItem, UpdateItem, DeleteItem, AddToCart, Cart, \
    OrderView, delete_one_by_one, Checkout, delete_from_cart, StatisticsView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('items/add/', CreateItem.as_view(), name="create_item"),
    path('item/<int:pk>/', ItemView.as_view(), name="item_view"),
    path('item/<int:pk>/update/', UpdateItem.as_view(), name="update_item"),
    path('item/<int:pk>/delete/', DeleteItem.as_view(), name="delete_item"),
    path('cart/<int:pk>/', AddToCart.as_view(), name='add_to_cart'),
    path('cart/', Cart.as_view(), name='cart'),
    path('cart/<int:pk>/delete/', delete_from_cart, name='delete_from_cart'),
    path('cart/<int:pk>/delete1/', delete_one_by_one, name='delete_one_from_cart'),
    path('checkout/', Checkout.as_view(), name='checkout'),
    path('orders/', OrderView.as_view(), name='orders'),
    path('statistics/', StatisticsView.as_view(), name='statistics')
]

shop/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Sum, F

# Create your models here.

CATEGORIES_CHOICES = [('other', 'Other'), ('fishing', 'Fishing'), ('hunting', 'Hunting'), ('skiing', 'Skiing'),
                      ('diving', 'Diving')]


class Item(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False, verbose_name="Name")
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name="Description")
    category = models.CharField(max_length=50, null=False, blank=False, choices=CATEGORIES_CHOICES,
                                verbose_name="Category", default=CATEGORIES_CHOICES[0][0])
    balance = models.PositiveIntegerField(verbose_name="Balance")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Price")

    def __str__(self):
        return f"{self.id}. {self.name}: {self.category}"

    class Meta:
        db_table = "items"
        verbose_name = "Item"
        verbose_name_plural = "Items"


class Order(models.Model):
    username = models.CharField(max_length=50, null=False, blank=False, verbose_name="Username")
    phonenumber = models.CharField(max_length=50, null=False, blank=False, verbose_name="Phone number")
    address = models.CharField(max_length=1000, null=False, blank=False, verbose_name="Address")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created at")
    items = models.ManyToManyField('webapp.Item', related_name='orders', verbose_name='Products',
                                      through='webapp.ItemsOrders', through_fields=['order', 'item'])
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="orders",
                             verbose_name='User', null=True, blank=True)

    def get_total(self):
        total = self.itemsorders.aggregate(total=Sum(F("quantity") * F("item__price")))
        return total["total"]

    def __str__(self):
        return f"{self.id}. {self.username}: {self.phonenumber}"

    class Meta:
        db_table = "order"
        verbose_name = "Order"
        verbose_name_plural = "Orders"


class ItemsOrders(models.Model):
    item = models.ForeignKey("webapp.Item", on_delete=models.CASCADE,
                             related_name='itemsorders', verbose_name="Item")
    order = models.ForeignKey("webapp.Order", on_delete=models.CASCADE, related_name='itemsorders',
                              verbose_name="Order")
    quantity = models.PositiveIntegerField(verbose_name="Amount")

    def __str__(self):
        return f"{self.id}. {self.item}: {self.order}: {self.quantity}"

    def get_sum(self):
        return self.quantity * self.item.price

    class Meta:
        verbose_name = "Confirmed order"
        verbose_name_plural = "Confirmed orders"

shop/webapp/forms.py
from django import forms
from webapp.models import Item, Order
from django.forms import widgets


class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = ["name", "description", "category", "balance", 'price']
        widgets = {
            "description": widgets.Textarea(attrs={"placeholder": "enter description"}),
            "category": widgets.RadioSelect,
        }


class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='Search')


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ["username", "phonenumber", "address"]
        widgets = {
            "address": widgets.Textarea(attrs={"placeholder": "enter address"})
        }


class AddToBasketForm(forms.Form):
    qty = forms.IntegerField(label="Choose amount:")

shop/webapp/views/basket.py
from django.contrib import messages
from django.shortcuts import redirect, get_object_or_404, HttpResponseRedirect, render
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView, ListView, CreateView

from webapp.models import Item, ItemsOrders, Order
from webapp.forms import OrderForm


class AddToCart(View):

    def post(self, request, *args, **kwargs):
        quantity = int(request.POST.get('qty'))
        pk = self.kwargs.get('pk')
        item = get_object_or_404(Item, pk=pk)
        if not request.session.get('pk') or not request.session.get('qty'):
            request.session['pk'] = []
            request.session['qty'] = []
        id_list = request.session['pk']
        qty_list = request.session['qty']

        if pk not in id_list:
            id_list.append(pk)
            if item.balance >= quantity:
                qty = quantity
                qty_list.append(qty)
                messages.success(request, f'Item "{item.name}" added to a cart, {qty} pieces')
            else:
                messages.error(request, f'Item {item.name} balance is not enough to add to your cart')

        elif pk in id_list:
            if item.balance >= quantity:
                index = id_list.index(pk)
                qty = qty_list[index]
                qty = qty + quantity
                qty_list[index] = qty
                messages.success(request, f'Item "{item.name}" added to a cart, {qty} pieces')
            else:
                messages.error(request, f'Item {item.name} balance is not enough to add to your cart')

        request.session['pk'] = id_list
        request.session['qty'] = qty_list

        return redirect(reverse('webapp:index'))

    def get(self, request, *args, **kwargs):
        quantity = 0
        pk = self.kwargs.get('pk')
        item = get_object_or_404(Item, pk=pk)
        if not request.session.get('pk') or not request.session.get('qty'):
            request.session['pk'] = []
            request.session['qty'] = []
        id_list = request.session['pk']
        qty_list = request.session['qty']
        if pk not in id_list:
            id_list.append(pk)
            if item.balance > 0:
                qty = quantity + 1
                qty_list.append(qty)
                messages.success(request, f'Item "{item.name}" added to a cart, {qty} pieces')
            else:
                messages.error(request, f'Item {item.name} balance is not enough to add to your cart')

        elif pk in id_list:
            if item.balance > 0:
                index = id_list.index(pk)
                qty = qty_list[index]
                qty = qty + 1
                qty_list[index] = qty
                messages.success(request, f'Item "{item.name}" added to a cart, {qty} pieces')
            else:
                messages.error(request, f'Item {item.name} balance is not enough to add to your cart')

        request.session['pk'] = id_list
        request.session['qty'] = qty_list

        return redirect(reverse('webapp:index'))


class Cart(TemplateView):
    template_name = 'carts/cart.html'

    def get(self, request, *args, **kwargs):
        items = []
        total_sum = 0
        items_sum = []
        form = OrderForm
        if request.session.get('pk'):
            id_list = request.session['pk']
            qty_list = request.session['qty']
            i = 0

            for pk in id_list:
                product = dict()
                item = get_object_or_404(Item, pk=pk)
                product['name'] = item.name
                product['pk'] = item.pk
                product['price'] = item.price
                qty = qty_list[i]
                product['qty'] = qty
                p_sum = item.price * qty
                product['items_sum'] = p_sum
                items_sum.append(p_sum)
                items.append(product)
                i += 1
            for k in items_sum:
                total_sum += k
            request.session['pk'] = id_list
            request.session['qty'] = qty_list
        return render(request, 'carts/cart.html', {'items': items, 'total_sum': total_sum,
                                                   'form': form})


def delete_from_cart(request, pk):
    id_list = request.session.get('pk')
    item = get_object_or_404(Item, pk=pk)
    index = id_list.index(pk)
    id_list.remove(pk)
    qty_list = request.session.get('qty')
    quantity = qty_list[index]
    qty_list.remove(quantity)
    request.session['pk'] = id_list
    request.session['qty'] = qty_list
    messages.warning(request, f'Item {item.name} was successfully removed from the cart')

    return redirect('webapp:cart')


def delete_one_by_one(request, pk):
    item = get_object_or_404(Item, pk=pk)
    id_list = request.session.get('pk')
    index = id_list.index(pk)
    qty_list = request.session.get('qty')
    quantity = qty_list[index]
    if quantity > 1:
        new_quantity = quantity - 1
        qty_list[index] = new_quantity
        request.session['pk'] = id_list
        request.session['qty'] = qty_list
        messages.warning(request, f'1 piece of {item.name} was removed from the cart')
    else:
        id_list.remove(pk)
        qty_list.remove(quantity)
        request.session['pk'] = id_list
        request.session['qty'] = qty_list
        messages.warning(request, f'Item {item.name} was successfully removed from the cart')

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


class Checkout(CreateView):
    model = Order
    template_name = 'carts/cart.html'
    form_class = OrderForm

    def form_valid(self, form):
        self.object = form.save()
        if self.request.user.is_authenticated:
            self.object.user = self.request.user
        order = ItemsOrders
        for i in range(len(self.request.session['pk'])):
            order.objects.create(quantity=self.request.session['qty'][i], order_id=self.object.pk,
                                 item_id=self.request.session['pk'][i])
        id_list = self.request.session['pk']
        id_list.clear()
        self.request.session['pk'] = id_list
        qty_list = self.request.session['qty']
        qty_list.clear()
        self.request.session['pk'] = qty_list
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:index')


class OrderView(ListView):
    template_name = 'carts/orderview.html'
    model = ItemsOrders
    context_object_name = 'itemsorders'

    def get_queryset(self, *args, **kwargs):
        user = self.request.user.username
        return ItemsOrders.objects.filter(order__username=user)

shop/webapp/views/items.py
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, DeleteView, UpdateView
from django.db.models import Q
from django.utils.http import urlencode

from webapp.models import Item
from webapp.forms import ItemForm, SearchForm, AddToBasketForm


class IndexView(ListView):
    model = Item
    template_name = "items/index.html"
    context_object_name = "items"
    ordering = 'name'
    paginate_by = 5

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        self.answer_form = self.get_answer_form()
        self.answer_value = self.get_answer_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        if self.search_value:
            return Item.objects.filter(
                Q(name__icontains=self.search_value) | Q(description__icontains=self.search_value))
        return Item.objects.filter(balance__gt=0)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["form"] = self.form
        context['form2'] = AddToBasketForm

        if self.search_value:
            query = urlencode({'search': self.search_value})
            context['query'] = query
            context['search'] = self.search_value
        return context

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get("search")

    def get_answer_form(self):
        return AddToBasketForm(self.request.GET)

    def get_answer_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get("answer")


class ItemView(TemplateView):
    template_name = "items/item_view.html"

    def get_context_data(self, **kwargs):
        pk = kwargs.get("pk")
        item = get_object_or_404(Item, pk=pk)
        kwargs["item"] = item
        kwargs['form2'] = AddToBasketForm
        return super().get_context_data(**kwargs)


class CreateItem(CreateView):
    template_name = 'items/create_item.html'
    model = Item
    form_class = ItemForm
    permission_required = 'webapp.add_item'

    def get_success_url(self):
        return reverse('webapp:item_view', kwargs={'pk': self.object.pk})


class UpdateItem(UpdateView):
    model = Item
    form_class = ItemForm
    context_object_name = 'item'
    template_name = 'items/update.html'
    permission_required = 'webapp.change_item'

    def get_success_url(self):
        return reverse('webapp:item_view', kwargs={'pk': self.object.pk})


class DeleteItem(DeleteView):
    model = Item
    context_object_name = 'item'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_item'

shop/webapp/views/statistic.py
from django.views.generic import TemplateView
import time, datetime


class StatisticsView(TemplateView):
    template_name = 'statistics.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        statistics = self.request.session['statistics']
        now = time.time()
        seconds = statistics['entry_time']
        time_diff = now - seconds
        time_format = str(datetime.timedelta(seconds=time_diff))
        context['statistics'] = {'time': time_format, 'count': statistics['count']}
        return context

shop/webapp/templates/items/create_item.html
{% extends "base.html" %}
{% block title %}Add item{% endblock %}

{% block content %}
    <div class="container">
        <h1>New item</h1>
        <form action="" method="post">
            {% include "partial/form.html" with button_text="Save" %}
        </form>
    </div>
{% endblock %}

shop/webapp/templates/items/index.html
{% extends "base.html"%}
{% load static %}
{% block title %}Home{% endblock %}
{% block nav_add %}
    {% if perms.webapp.add_item  %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:create_item" %}">New item</a>
        </li>
    {% endif %}
         <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:cart" %}">My cart</a>
        </li>
    {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:orders" %}">My orders</a>
        </li>
    {% endif %}
    <li class="nav-item">
        <a class="nav-link" href="{% url "webapp:statistics" %}">Statistics</a>
    </li>


{% endblock %}
{% block content %}

<div class="container">
    <div><h1>List of items</h1></div>
    <div class="mt-3">
        {% include "partial/search.html" %}
    </div>
    <div class="row">
        {% for item in items %}
            <div class="col col-md-4 mt-2">
                    <div class="card p-2 mb-2">
                        <div class="card-body">
                            <a href="{% url 'webapp:item_view' item.pk %}"><h4 class="card-title mt-2">{{ item.name }}</h4></a>
                            <p class="card-text">Price: {{ item.price }} $</p>
                            <p class="card-text">Category: {{ item.get_category_display }}</p>
                            <form action="{% url 'webapp:add_to_cart' item.pk %}" method="post">
                                {%  include 'partial/form2.html' with button_text='Add to cart'%}
                            </form>
                            <a href="{% url "webapp:add_to_cart" item.pk %}">
                                <button type="submit" class="btn btn-outline-secondary mt-2" value="Add to cart">Add to cart 1 item</button>
                            </a>


                        </div>
                    </div>
            </div>
        {% endfor %}
    </div>
{% if is_paginated %}
        {% include "partial/pagination.html" %}
    {% endif %}
</div>


{% endblock %}

shop/webapp/templates/items/item_view.html
{% extends "base.html"%}
{% load static %}
{% block title %}Detailed info{% endblock %}
{% block nav_add %}
    {% if pers.webapp.add_item or perms.webapp.change_item or perms.webapp.delete_item %}
    <li class="nav-item">
        <a class="nav-link" href="{% url "webapp:create_item" %}">Add item</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url "webapp:update_item" item.pk %}">Update item</a>
    </li>
    <li class="nav-item">
        <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#ItemDeleteModal">Delete item</button>
    </li>
    {% endif %}
    <li class="nav-item">
        <a class="nav-link" href="{% url "webapp:add_to_cart" item.pk %}">Add to cart</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url "webapp:cart" %}">My cart</a>
    </li>

{% endblock %}
{% block content %}

<div class="container">
    <div class="card mt-4" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Item: {{ item.name }}</h5>
            <p class="card-text">Description: {{ item.description }}</p>
            <p class="card-text">Category: {{ item.get_category_display }}</p>
            <p class="card-text">Balance: {{ item.balance }} pieces</p>
            <p class="card-text">Price: {{ item.price }} $</p>
            <form action="{% url 'webapp:add_to_cart' item.pk %}" method="post">
                {% csrf_token %}
                {%  include 'partial/form2.html' with button_text='Add to cart'%}
            </form>
        </div>
    </div>
</div>

 <div class="modal fade" id="ItemDeleteModal" tabindex="-1" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="ItemDeleteModal">Confirmation</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure want to remove item {{ item.name }}?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                    <form action="{% url "webapp:delete_item" item.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Yes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

shop/webapp/templates/items/update.html
{% extends "base.html" %}
{% block title %}Update{% endblock %}

{% block content %}
    <div class="container">
        <h1>Update item</h1>
        <form action="" method="post">
            {% include "partial/form.html" with button_text="Save changes"%}
        </form>
    </div>
{% endblock %}